name: awada
services:
  ${SERVICE_NAME}:
    image: alpha.awada.systems/${IMAGE_NAME}:${VERSION}
    container_name: ${SERVICE_NAME}
    hostname: ${SERVICE_NAME}
    volumes:
      - project:/var/project/
      - awada:/opt/awada
      - spread-conf:/etc/spread/
      - awada-sockets:/opt/awada-sockets/
      - awada-snippets:/etc/nginx/snippets/
    restart: unless-stopped
    depends_on:
      - postgres
volumes:
  project:
  awada:
  spread-conf:
  awada-sockets:
  awada-snippets: