"""Project and Entity added

Revision ID: 2dd05ddd1671
Revises: 62b738edfab6
Create Date: 2025-01-21 10:51:59.995187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2dd05ddd1671'
down_revision: Union[str, None] = '62b738edfab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('obj_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('obj_type', sa.Enum('Location', 'TypeSubginery', 'TypeEnginery', 'Enginery', name='entityobjecttype'), nullable=True),
    sa.Column('obj_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_id'), 'entity', ['id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sa.Enum('Spread', 'Cloud', 'Custom', name='projecttype'), nullable=False),
    sa.Column('connection_params', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_entity_id'), table_name='entity')
    op.drop_table('entity')
    # ### end Alembic commands ###
